export const SAFE_AREA_VIEW_INSETS = 'SAFE_AREA_VIEW_INSETS';
export const UPDATE_SERVER_STATUS = 'UPDATE_SERVER_STATUS';
export const UPDATE_APP_STATUS = 'UPDATE_APP_STATUS';
export const UPDATE_APP_MODAL_FIELDS = 'UPDATE_APP_MODAL_FIELDS';
