export const SAVE_USER_INFO = 'SAVE_USER_INFO'
export const SAVE_SERVER_URL = 'SAVE_SERVER_URL'
export const SAVE_USER_PERMISSION = 'SAVE_USER_PERMISSION';
export const RESET_PERMISSION_STATE = 'RESET_PERMISSION_STATE';
export const SAVE_SCHOOL_NAME = 'SAVE_SCHOOL_NAME';
export const SAVE_PASSWORD_CHANGE = 'SAVE_PASSWORD_CHANGE';
export const UPDATE_AUTH_USER_DETAILS = 'UPDATE_AUTH_USER_DETAILS';
