export default {
  logIn: 'login',
  logout: 'logout',
  getrole: 'getrole',
  changepassword: 'changepassword',
  getSchooldetail: 'config/getschooldetail',
  validateServerUrl: 'config/validateServerUrl',
  getUserPermissions: 'roles/getuserpermissions',
  getNotificationsList: 'notification/list',
  triggerEvent: 'events/triggerEvent',
  userInfo: 'userinfo',
  stopNotifications: 'events/notification/stop',
  notificationStatus: 'events/notification/status',
  getAllZones: 'setup/getAllZones',
  sendPage: 'startPaging',
  dayTypes: 'daytypes/getDayTypeData',
  calendarData: id => `schedules/calendar?id=${id}`,
  timeDetails: 'time-details',
  addScheduleData: 'schedules/addScheduleData',
  getDeviceByRoomId: (id) =>
  `devices/getDeviceByDeviceTypeRoom/${id}`,
  alertToken:(id) =>
  `alerts/token?data=${id}`,
  activeAlerts :'notification/alertlogs',
  zonesListPaging:'setup/getZoneInforFront',
  csrfToken:'csrftoken',
  getToken:'getToken',
  getSSOCredsMobile:'get-sso-creds-mobile',
  secureCheckIn:'events/info',
  lockDashboardData :'lockdown/room-status',
  endLockdown:'lockdown/end',
  mapsList:'setup/allMap',
  getConfiguredButtons:'relatedEvents',
  acknowledgeSafeAlert:'alerts/acknowledge',
  lockdownSummary: (id) => `lockdown/summary?alertId=${id}`,
  checkEscalateActions : 'events/getEventActionMapping'
};
